feature/MSK20FRONT-10-display-connected-offerings
egorka13/nc-csrd pull request #9
Opened 2020-12-14 18:21 UTC by ImRasen

На самом деле здесь Connected Offerings и частичная реализация Available Offerings

2020-12-14 21:19 UTC, Georgitto reviewed
Я просмотрел, в большей мере обращал внимание на изменение общих файлов, но не увидел того, что могло бы привести к ошибке.

2020-12-14 21:40 UTC, egorka13 requested changes
Замечаний особо нет, хорошая реализация подсчета scrollRatio для определения момента, когда мы горизонтально прокручиваем до конца блока

2020-12-14 21:40 UTC, egorka13 commented on client/less/common/color.less
> -@csrd-background: #F3F3F3;
А этот цвет разве не используется для заднего фона страницы модуля?

2020-12-14 21:47 UTC, egorka13 commented on client/less/components/main.less
> +  width: 210px;
Вы договорились, что в твоей ветке меняется ширина сайдбара?

2020-12-15 13:09 UTC, ImRasen commented on client/less/common/color.less
> -@csrd-background: #F3F3F3;
Вроде он дублировался

2020-12-15 13:10 UTC, ImRasen commented on client/less/components/main.less
> +  width: 210px;
Еще нет... + не договорились о названии блоков в сайдбаре (у меня, например, не ROE, а Product Manager

2020-12-15 13:11 UTC, egorka13 commented on client/less/common/color.less
> -@csrd-background: #F3F3F3;
А, хорошо, вижу

2020-12-15 13:17 UTC, egorka13 approved these changes

2020-12-15 13:20 UTC, merged